require_relative 'consumption/generate_response'
require_relative 'consumption/interaction'
require_relative 'consumption/mock_producer'
require_relative 'consumption/mock_service'
require_relative 'consumption/app_manager'
