# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/internal/deps/services/pet_store/grpc/pet_store.proto

require 'google/protobuf'

descriptor_data = "\n:spec/internal/deps/services/pet_store/grpc/pet_store.proto\x12\x0cpet_store.v1\"U\n\x03Pet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04tags\x18\x03 \x03(\t\x12&\n\x06\x63olors\x18\x04 \x03(\x0b\x32\x16.pet_store.v1.PetColor\"\x9d\x01\n\x08PetColor\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\x12\n\nrelates_to\x18\x03 \x03(\t\x12/\n\x05\x63olor\x18\x04 \x01(\x0e\x32 .pet_store.v1.PetColor.BaseColor\")\n\tBaseColor\x12\x07\n\x03RED\x10\x00\x12\t\n\x05GREEN\x10\x01\x12\x08\n\x04\x42LUE\x10\x02\"\x1c\n\x0ePetByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x99\x01\n\x0bPetResponse\x12\x1e\n\x03pet\x18\x01 \x01(\x0b\x32\x11.pet_store.v1.Pet\x12\x39\n\x08metadata\x18\x02 \x03(\x0b\x32\'.pet_store.v1.PetResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32J\n\x04Pets\x12\x42\n\x07PetById\x12\x1c.pet_store.v1.PetByIdRequest\x1a\x19.pet_store.v1.PetResponseB\x1f\xea\x02\x1cPetStore::Grpc::PetStore::V1b\x06proto3" # rubocop:disable Layout/LineLength

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module PetStore
  module Grpc
    module PetStore
      module V1
        Pet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.Pet").msgclass # rubocop:disable Layout/LineLength
        PetColor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.PetColor").msgclass # rubocop:disable Layout/LineLength
        PetColor::BaseColor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.PetColor.BaseColor").enummodule # rubocop:disable Layout/LineLength
        PetByIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.PetByIdRequest").msgclass # rubocop:disable Layout/LineLength
        PetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.PetResponse").msgclass # rubocop:disable Layout/LineLength
      end
    end
  end
end
