# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: pet_store.proto for package 'PetStore.Grpc.PetStore.V1'

require "grpc"
require_relative "pet_store_pb"

module PetStore
  module Grpc
    module PetStore
      module V1
        module Pets
          class Service
            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = "pet_store.v1.Pets"

            rpc :PetById, ::PetStore::Grpc::PetStore::V1::PetByIdRequest, ::PetStore::Grpc::PetStore::V1::PetResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
