source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pry'
end

gem 'rake'
gem 'rack', '>= 3.1.5'
gem 'sqlite3'
gem 'sequel'
gem 'sinatra', '>= 4.0.0'
