source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~> 2.2', '>= 2.2.6.4'
gem 'sqlite3'
gem 'sequel'
gem 'sinatra'
