$: << File.join(File.dirname(__FILE__), 'lib')

task default: 'pact:verify'

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new('pact:verify') do |task|
  task.pattern = 'spec/pact/consumers/*_spec.rb'
  task.rspec_opts = ['-t pact', '--require rails_helper']
end
