source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pact_broker-client'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~>2.2'
gem 'httparty', '>= 0.21.0'
