source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pact_broker-client'
  gem 'pry'
end

gem 'rake'
gem 'rack', '~> 3.0', '>= 3.0.0'
gem 'httparty', '>= 0.21.0'
